Performance comparison

In [2]:
import numpy as np
import time

size = 1000000

# Python list
list1 = range(size)
list2 = range(size)

start = time.time()
result = [(x + y) for x, y in zip(list1, list2)]
print("Python list took:", time.time() - start)

# NumPy array
array1 = np.arange(size)
array2 = np.arange(size)

start = time.time()
result = array1 + array2
print("NumPy array took:", time.time() - start)

Python list took: 0.24404644966125488
NumPy array took: 0.008252859115600586


Creating Arrays

In [3]:
# From Python list
arr1 = np.array([1, 2, 3, 4, 5])

# Array of zeros
arr2 = np.zeros(5)

# Array of ones
arr3 = np.ones((2, 3))  # 2 rows, 3 columns

# Array with a range
arr4 = np.arange(0, 20, 2)  # start, stop, step

# Random array
arr5 = np.random.rand(3, 3)  # 3x3 random values between 0-1

# Identity matrix
arr6 = np.eye(4)  # 4x4 identity matrix

# Linspace - evenly spaced numbers
arr7 = np.linspace(0, 1, 5)  # 5 numbers from 0 to 1

Using Arrays and Scalars

In [4]:
arr = np.array([1, 2, 3, 4])

# Scalar operations
print(arr + 5)      # [6 7 8 9]
print(arr * 2)      # [2 4 6 8]
print(1 / arr)      # [1.   0.5  0.33333333 0.25]

# Array-array operations
arr2 = np.array([5, 6, 7, 8])
print(arr + arr2)   # [ 6  8 10 12]
print(arr * arr2)   # [ 5 12 21 32]

[6 7 8 9]
[2 4 6 8]
[1.         0.5        0.33333333 0.25      ]
[ 6  8 10 12]
[ 5 12 21 32]


Indexing Arrays

In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Single element
print(arr[0, 1])  # 2 (row 0, column 1)

# Slicing
print(arr[:2, 1:])  # First 2 rows, columns from 1 onward
# [[2 3]
#  [5 6]]

# Boolean indexing
print(arr[arr > 5])  # [6 7 8 9]

# Fancy indexing
print(arr[[0, 2]])  # First and third rows
# [[1 2 3]
#  [7 8 9]]

2
[[2 3]
 [5 6]]
[6 7 8 9]
[[1 2 3]
 [7 8 9]]


Array Transposition

In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Transpose
print(arr.T)
# [[1 4]
#  [2 5]
#  [3 6]]

# For higher dimensions, use transpose with axes
arr3d = np.arange(8).reshape((2,2,2))
print(arr3d.transpose(1,0,2))

[[1 4]
 [2 5]
 [3 6]]
[[[0 1]
  [4 5]]

 [[2 3]
  [6 7]]]


Universal Array Functions (ufuncs)

In [7]:
arr = np.array([1, 2, 3, 4])

# Math operations
print(np.sqrt(arr))     # Square root
print(np.exp(arr))      # Exponential
print(np.sin(arr))      # Trigonometric sine
print(np.log(arr))      # Natural logarithm

# Statistical operations
print(np.mean(arr))     # 2.5
print(np.std(arr))      # Standard deviation
print(np.sum(arr))      # 10
print(np.max(arr))      # 4

[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[0.         0.69314718 1.09861229 1.38629436]
2.5
1.118033988749895
10
4


Array Processing

In [8]:
# Vectorization - avoid loops
arr = np.random.rand(1000000)

# Slow Python way
def slow_square(x):
    result = np.zeros(len(x))
    for i in range(len(x)):
        result[i] = x[i] ** 2
    return result

# Fast NumPy way
def fast_square(x):
    return x ** 2

# Conditional operations
arr = np.array([1, 2, 3, 4, 5])
print(np.where(arr > 3, arr, 0))  # [0 0 0 4 5]

# Aggregations
matrix = np.random.rand(5, 5)
print(matrix.sum(axis=0))  # Sum columns
print(matrix.mean(axis=1)) # Mean of rows

[0 0 0 4 5]
[2.73273282 2.4935605  2.65051646 2.41214662 2.80303776]
[0.44662635 0.53057716 0.39041257 0.74805946 0.50272329]


Array Input and Output

In [9]:
# Saving and loading
arr = np.arange(10)

# Save to binary file
np.save('my_array.npy', arr)

# Load from binary file
loaded_arr = np.load('my_array.npy')

# Save/load text files
np.savetxt('array.txt', arr, delimiter=',')
loaded_from_txt = np.loadtxt('array.txt', delimiter=',')

# Save multiple arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
np.savez('arrays.npz', a=arr1, b=arr2)

# Load multiple arrays
loaded = np.load('arrays.npz')
print(loaded['a'])  # [1 2 3]
print(loaded['b'])  # [4 5 6]

[1 2 3]
[4 5 6]


Exercise on Numpy
1.Create a 5x5 array with random values and find the minimum and maximum values

2.Create a 10x10 array with random values and normalize it (0-1)

3.Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

4.Find the most frequent value in a random array of size 100

5.Create a checkerboard 8x8 matrix using slicing and striding